import {readFile,writeFile} from 'node:fs/promises';
const data=await readFile(new URL('../assets/arms/arms.glb',import.meta.url));
await writeFile(new URL('../src/arms-asset.js',import.meta.url),'// Generated by scripts/embed-arms.mjs; see assets/arms/SOURCE.md.\nexport default '+JSON.stringify(data.toString('base64'))+';\n');
