// Bake the CC0 FBX into static geometry and inline textures for offline play.
import { readFile, writeFile } from 'node:fs/promises';
import { FBXLoader } from '../node_modules/three/examples/jsm/loaders/FBXLoader.js';
import { mergeVertices } from '../node_modules/three/examples/jsm/utils/BufferGeometryUtils.js';
const root=new URL('../assets/ak47/',import.meta.url);
const file=await readFile(new URL('SKM_AK47.fbx',root));
const model=new FBXLoader().parse(file.buffer.slice(file.byteOffset,file.byteOffset+file.byteLength),'');
model.updateMatrixWorld(true);
const meshes=[];
model.traverse(mesh=>{
  if(!mesh.isMesh)return;
  const geometry=mesh.geometry.clone();
  geometry.applyMatrix4(mesh.matrixWorld);
  // FBX UV islands occupy an offset tile; the supplied atlas repeats per tile.
  const uv=geometry.attributes.uv;
  for(let i=0;i<uv.count;i++)uv.setXY(i,uv.getX(i)%1,uv.getY(i)%1);
  geometry.rotateY(Math.PI);geometry.scale(.014,.014,.014);geometry.translate(0,-.075,.068);
  for(const name of Object.keys(geometry.attributes))if(!['position','normal','uv'].includes(name))geometry.deleteAttribute(name);
  geometry.clearGroups();
  meshes.push(mergeVertices(geometry).toJSON());
});
const textures={};
for(const name of ['color','normal','rmao'])textures[name]='data:image/jpeg;base64,'+(await readFile(new URL(name+'.jpg',root))).toString('base64');
await writeFile(new URL('../src/ak47-asset.js',import.meta.url),'// Generated by scripts/prepare-ak.mjs. Stein Games, CC0.\nexport default '+JSON.stringify({meshes,textures})+';\n');
