// Preserve embedded diffuse textures, cutout foliage and vertex colors for offline play.
import { readFile, writeFile } from 'node:fs/promises';
import { Box3, Vector3 } from 'three';
import { GLTFLoader } from '../node_modules/three/examples/jsm/loaders/GLTFLoader.js';
const root=new URL('../assets/nature/',import.meta.url),models={},textures={},materials={};
globalThis.ProgressEvent??=class ProgressEvent {constructor(type,props){Object.assign(this,{type},props);}};
for(const name of ['pine','rock','bush']){
  const file=await readFile(new URL(name+'.glb',root));
  const length=file.readUInt32LE(12),json=JSON.parse(file.subarray(20,20+length).toString()),binary=file.subarray(28+length);
  for(const material of json.materials){
    const key=name+':'+material.name,pbr=material.pbrMetallicRoughness;
    const image=json.images[json.textures[pbr.baseColorTexture.index].source],view=json.bufferViews[image.bufferView];
    textures[key]=`data:${image.mimeType};base64,`+binary.subarray(view.byteOffset||0,(view.byteOffset||0)+view.byteLength).toString('base64');
    materials[key]={texture:key,cutout:material.alphaMode==='BLEND',vertexColors:false};
    delete pbr.baseColorTexture;delete material.normalTexture;
  }
  json.buffers[0].uri='data:application/octet-stream;base64,'+binary.toString('base64');
  delete json.images;delete json.textures;
  const {scene}=await new GLTFLoader().parseAsync(JSON.stringify(json),'');scene.updateMatrixWorld(true);
  const bounds=new Box3().setFromObject(scene),center=bounds.getCenter(new Vector3()),meshes=[],keys=[];
  let trunk=null;
  scene.traverse(mesh=>{
    if(!mesh.isMesh)return;
    const key=name+':'+mesh.material.name,geometry=mesh.geometry.clone().applyMatrix4(mesh.matrixWorld);
    geometry.translate(-center.x,-bounds.min.y,-center.z);
    materials[key].vertexColors=!!geometry.attributes.color;
    if(name==='pine'&&!materials[key].cutout){
      const base=new Box3(),position=geometry.attributes.position;
      for(let i=0;i<position.count;i++){const p=new Vector3().fromBufferAttribute(position,i);if(p.y<.8)base.expandByPoint(p);}
      if(base.isEmpty())throw new Error('Missing pine trunk base');
      trunk={min:base.min.toArray(),max:base.max.toArray()};
    }
    meshes.push(geometry);keys.push(key);
  });
  if(trunk){
    const x=(trunk.min[0]+trunk.max[0])/2,z=(trunk.min[2]+trunk.max[2])/2;
    for(const geometry of meshes)geometry.translate(-x,0,-z);
    trunk.min[0]-=x;trunk.max[0]-=x;trunk.min[2]-=z;trunk.max[2]-=z;
  }
  models[name]={meshes:meshes.map(g=>g.toJSON()),materials:keys,namespace:'nature',size:bounds.getSize(new Vector3()).toArray(),trunk};
  console.log(name,models[name].size,trunk||'');
}
await writeFile(new URL('../src/nature-asset.js',import.meta.url),'// Generated by scripts/prepare-nature.mjs. Quaternius, CC0; see assets/nature/README.md.\nexport default '+JSON.stringify({models,textures,materials})+';\n');
