import {readFile,writeFile} from 'node:fs/promises';
const data={};
for(const name of ['usp','awp','m4a1','glock'])data[name]=(await readFile(new URL('../assets/weapons/'+name+'.glb',import.meta.url))).toString('base64');
await writeFile(new URL('../src/weapons-asset.js',import.meta.url),'// Generated by scripts/prepare-weapons.mjs; see assets/weapons/SOURCE.md.\nexport default '+JSON.stringify(data)+';\n');
